
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import com.mysql.jdbc.Statement;
import java.util.HashSet;
import java.util.Set;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Maxi
 */
public class Product extends javax.swing.JFrame {
    public void mostrarDatosTabla(String Valor){
    Conectar conn = new Conectar();
    conn.conexion();
    //DefaultTableModel modelo;
    //modelo = new DefaultTableModel();
    DefaultTableModel modelo = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    
    };
    modelo.addColumn("ID_PRODUCTO");
    modelo.addColumn("CATEGORÍA");
    modelo.addColumn("DESCRIPCION");
    modelo.addColumn("PRECIO");
    modelo.addColumn("CANTIDAD");
    
    
    String sql;
    
        if (Valor.equals("")) {
            //Ejecutamos la consulta
            sql= "select id_producto,categoria,descripcion,precio,cantidad from productos ORDER BY categoria ASC";
        }else{
            //Ejecutamos la consulta para buscar 
            sql= "select id_producto,categoria,descripcion,precio,cantidad from productos where descripcion like '%"+Valor+"%'";
        
        }
    
        String[] datos = new String[5];
        com.mysql.jdbc.Statement st;
        
        try {
            ResultSet rs = (ResultSet) conn.Consultar(sql);
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

    }

    public void limpiar(){
     //Método que no devuelve nada. Sirve para limpiar las cajas
     jComboBox1.setSelectedIndex(0); //Colocar el comboBox en el inicio
     jDescripcion.setText(""); //Set para poner un valor en estos casos vacio
     jPrecio.setText("");
     jCantidad.setText("");
     jTextField2.setText("");
     
    
    }
    public Product() {
        initComponents();
        mostrarDatosTabla("");
        
        
        
//        //Contar cantidad de columnas
//        Conectar conn = new Conectar();
//        Connection cn = (Connection) conn.conexion();
//        String sqll;
//        sqll= "select * from productos";
//        Statement st;
//        try {
//            
//            st= (Statement) cn.createStatement();
//            ResultSet rs;
//            rs = st.executeQuery(sqll);
//        //ResultSet rs = (ResultSet) conn.Consultar(sqll);
//        int total = 0;
//        while (rs.next()) {
//            //Obtienes la data que necesitas...
//            total++;
//        }
//        
//            if (total>=1000) { //Modificar este valor para ponerlo en fase beta
//                
//                JOptionPane.showMessageDialog(null, "Finalizó la fase de prueba, contactarse con el programador");
//                jButton1.setEnabled(false);
//            }else{
//                JOptionPane.showMessageDialog(null, "Programa sin licencia.\nContactarse con el programador para adquirir la version full.\n E-mail: mmlazo54@gmail.com");
//                
//            }
//        } catch (Exception e) {
//        }
        
            
        
        
        ComboBoxx opciones = new ComboBoxx();
        opciones.mostrar_combo(jComboBox1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jDescripcion = new javax.swing.JTextField();
        jPrecio = new javax.swing.JTextField();
        jCantidad = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel1.setText("ID:");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel2.setText("CATEGORÍA:");

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel3.setText("DESCRIPCIÓN:");

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel4.setText("PRECIO:");

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel5.setText("CANTIDAD:");

        jComboBox1.setForeground(new java.awt.Color(0, 51, 204));

        jDescripcion.setForeground(new java.awt.Color(0, 51, 204));

        jPrecio.setForeground(new java.awt.Color(0, 51, 204));
        jPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPrecioKeyTyped(evt);
            }
        });

        jCantidad.setForeground(new java.awt.Color(0, 51, 204));
        jCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCantidadActionPerformed(evt);
            }
        });
        jCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jCantidadKeyTyped(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Franklin Gothic Book", 1, 12)); // NOI18N
        jButton4.setText("Borrar");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        jLabel6.setText("BUSCAR POR DESCRIPCIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel6))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jTextField2.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, 164, Short.MAX_VALUE)
                                .addComponent(jDescripcion)
                                .addComponent(jPrecio)
                                .addComponent(jCantidad))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCantidadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Conectar con = new Conectar();
        Connection cn= (Connection) con.conexion();
        
        
        try {
            //Si el item del combo box es 0 o alguno está vacio entonces faltan campos, sino, Guardo consulta
            if (jComboBox1.getSelectedIndex()== 0||"".equals(jDescripcion.getText()) || "".equals(jPrecio.getText()) || "".equals(jCantidad.getText())  ) {
                JOptionPane.showMessageDialog(null, "Faltan campos","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            }else{
            PreparedStatement pst = (PreparedStatement)cn.prepareStatement("insert into productos (id_producto,categoria,descripcion,precio,cantidad) values(?,?,?,?,?)");
            pst.setInt(1, (int) (Math.random()*10000));
            pst.setString(2, (String) jComboBox1.getSelectedItem());
            pst.setString(3, jDescripcion.getText());
            pst.setString(4, jPrecio.getText());
            pst.setString(5, jCantidad.getText());
            pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Nuevo producto cargado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
             mostrarDatosTabla("");
             jButton1.setEnabled(false);
             jButton2.setEnabled(true);
            
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        limpiar();
        jButton2.setEnabled(false);
        jButton1.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int fila = jTable1.getSelectedRow();
        
        if(fila>=0){
            jTextField2.setText(jTable1.getValueAt(fila, 0) .toString());
            jComboBox1.setSelectedItem(jTable1.getValueAt(fila, 1) .toString());
            jDescripcion.setText(jTable1.getValueAt(fila, 2) .toString());
            jPrecio.setText(jTable1.getValueAt(fila, 3) .toString());
            jCantidad.setText(jTable1.getValueAt(fila, 4) .toString());
            jButton3.setEnabled(true);
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton4.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(null,"No seleccionó ninguna fila");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        //Modify the products:
        
        Conectar con = new Conectar();
        Connection cn= (Connection) con.conexion();
        
        
        try {
            //Si el item del combo box es 0 o alguno está vacio entonces faltan campos, sino, modifico registro
            if (jComboBox1.getSelectedIndex()== 0||"".equals(jDescripcion.getText()) || "".equals(jPrecio.getText()) || "".equals(jCantidad.getText())  ) {
                JOptionPane.showMessageDialog(null, "Seleccionar algún producto de la tabla","Error",JOptionPane.INFORMATION_MESSAGE);
            }else{
            PreparedStatement pst = (PreparedStatement)cn.prepareStatement("update productos set id_producto = '"+jTextField2.getText()+"',categoria = '"+(String) jComboBox1.getSelectedItem()+"',descripcion = '"+jDescripcion.getText()+"',precio = '"+jPrecio.getText()+"',cantidad = '"+jCantidad.getText()+"' where id_producto ='"+jTextField2.getText()+"' ");
            
            pst.executeUpdate();
             JOptionPane.showMessageDialog(null, "Producto actualizado","Mensaje",JOptionPane.INFORMATION_MESSAGE);
             jButton3.setEnabled(false);
             jButton2.setEnabled(true);
             jButton4.setEnabled(false);
             mostrarDatosTabla("");
             limpiar();
            
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        mostrarDatosTabla(jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPrecioKeyTyped
        // SOLO DEJE ESCRIBIR NÚMEROS Y EL PUNTO
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c !='.'))
            evt.consume();
        
    
    }//GEN-LAST:event_jPrecioKeyTyped

    private void jCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCantidadKeyTyped
        // TODO add your handling code here:
            char c = evt.getKeyChar();
        if(c<'0' || c>'9')evt.consume();
    
    }//GEN-LAST:event_jCantidadKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         Conectar con = new Conectar();
        Connection cn= (Connection) con.conexion();
        
        int fila = jTable1.getSelectedRow();
        int id = Integer.parseInt(jTable1.getValueAt(fila,0).toString());
        
        int confirmar;
        
        try {
            confirmar = JOptionPane.showConfirmDialog(null,"¿Desea borrar el registro?");
            if(JOptionPane.OK_OPTION  == confirmar){
             String sql = "delete from productos where id_producto = "+id;
             PreparedStatement ps =(PreparedStatement) cn.prepareStatement(sql);
             JOptionPane.showMessageDialog(null,"El registro ha sido eliminado exitosamente","Operación Exitosa",JOptionPane.INFORMATION_MESSAGE);
             ps.executeUpdate();
             limpiar();
             mostrarDatosTabla("");
             jButton4.setEnabled(false);
             jButton3.setEnabled(false);
             jButton2.setEnabled(true);
                
            }
            else{
                   JOptionPane.showMessageDialog(null, "Eligió no eliminar el registro", "Operación cancelada", JOptionPane.INFORMATION_MESSAGE);
                mostrarDatosTabla("");
                jButton4.setEnabled(false);
                jButton3.setEnabled(false);
                jButton2.setEnabled(true);
                     }
        } catch (Exception e) {
            java.util.logging.Logger.getLogger(Product.class.getName()) .log(java.util.logging.Level.SEVERE,null,e);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jCantidad;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JTextField jDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jPrecio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
